version: "3.7"

services:
    advices-database:
        image: postgres
        container_name: advices-database
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=advices-database
        volumes: 
            - pgdata:/data/postgres

volumes: 
    pgdata:
        driver: local